# Generated by Django 5.1.7 on 2025-03-22 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='category',
            field=models.CharField(choices=[('Tech', 'Tech'), ('Life', 'Life'), ('Tutorial', 'Tutorial'), ('News', 'News')], default='Tech', max_length=50),
        ),
    ]
